services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-api
    environment:
      - JWT_SECRETS=${JWT_SECRETS}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3001:3001"